services:
  nodejs:
    from: 'node:4.2.1'

staging:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  port: 3001
  cmd: npm start
  env:
    - NODE_ENV=production
    - PORT=3001

tests:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  cmd: 'echo "...\e[32m..\e[0m.<strong>1</strong>..."'
  env:
    - NODE_ENV=production
