services:
  nodejs:
    from: 'node:0.12.2'

staging:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  port: 80
  cmd: npm start
  env:
    - NODE_ENV=production
    - PORT=80

tests:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  cmd: 'echo "...\e[32m..\e[0m.<strong>1</strong>..."'
  env:
    - NODE_ENV=production
